[metadata]
name = besser-governance-engine
version = 1.0.0
author = Luxembourg Institute of Science and Technology
description = BESSER Governance Decision Engine
long_description = file: README.md
long_description_content_type = text/markdown
project_urls =
    Documentation = https://besser-governance-engine.readthedocs.io/
    Source Code = https://github.com/BESSER-PEARL/GovernanceDecisionEngine
    Bug Tracker = https://github.com/BESSER-PEARL/GovernanceDecisionEngine/issues
keywords = agent, bot, governance
license = MIT

[options]
python_requires = >=3.10
packages = find:
install_requires =
    besser-agentic-framework==4.5.2
    governancedsl==0.1.2

[options.packages.find]
exclude =
    governance.tests
    governance.tests.*
